services:
  localstack:
    image: localstack:latest
    container_name: my_localstack
    ports:
      - "127.0.0.1:4566:4566" # localstack gateway
      - "4566-4599:4566-4599" # aws services port range
    environment:
      - SERVICES=s3, dynamodb, lambda, sqs, cloudwatch, ec2, 
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
    volumes:
      - "${LOCALSTACK_DATA_DIR:-./.localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
